### ISSUE TITLE
How to define multiple directories to include?

### ISSUE THREAD

**Issue by bartonhammond** [leanphp/behat-code-coverage#21]
1) the project has `php` files in multiple directories.  How do I define `include.directories`  when I have a list of them?
2) some of our php files have extension of 'inc'.  How can I include them?

With the following, I get this error:
```
~/projects/uwce/www (develop)$ composer wip
> vendor/bin/behat --config behat.yml --colors  --tags wip
In ScalarNode.php line 36:
  Invalid type for path "testwork.code_coverage.filter.whitelist.include.directories.src.prefix". Expected scalar, but got array.  
Script vendor/bin/behat --config behat.yml --colors  --tags wip handling the wip event returned with error code 1
~/projects/uwce/www (develop)$ 

```
My Extension definition
```
  LeanPHP\Behat\CodeCoverage\Extension:
      auth:       ~
      drivers:
        - local
      filter:
        forceCoversAnnotation:                false
        mapTestClassNameToCoveredClassName:   false
        whitelist:
          addUncoveredFilesFromWhitelist:     true
          processUncoveredFilesFromWhitelist: false
          include:
            directories:
              'src':
                prefix: ['modelViews', "utilities", "models", "modelRepositories","services", "controllers", "views"]
              'tests':
                prefix: 'src'
        blacklist:
          include:
            directories:
              'vendor':
                prefix: 'vendor'      
      report:
        format:   html
        options:
          target: build/behat-coverage
```

**Comment by bartonhammond** [comment]
I tried the following to no avail
```
    LeanPHP\Behat\CodeCoverage\Extension:
      auth:       ~
      drivers:
        - local
      filter:
        forceCoversAnnotation:                false
        mapTestClassNameToCoveredClassName:   false
        whitelist:
          addUncoveredFilesFromWhitelist:     true
          processUncoveredFilesFromWhitelist: false
          include:
            directories:
              'modelViews':
                'prefix': 'modelViews'
                'suffix': '.php'
              'utilities':
                'prefix': 'utilities'
                'suffix': '.php'
              'models1':
                'prefix': 'models'
                'suffix': '.php'
              'models2':
                'prefix': 'models'
                'suffix': '.inc'                
              'modelRepositories':
                'prefix': 'modelRepositories'
                'suffix': '.php'                
              'services':
                'prefix': 'services'
                'suffix': '.php'                
              'controllers1':
                'prefix': 'controllers'
                'suffix': '.inc'
              'controllers2':
                'prefix': 'controllers'
                'suffix': '.php'                                
              'views':
                'prefix': 'views'
                'suffix': '.php'                
```

**Comment by bartonhammond** [comment]
And then tried this:
```
    LeanPHP\Behat\CodeCoverage\Extension:
      auth:       ~
      drivers:
        - local
      filter:
        forceCoversAnnotation:                false
        mapTestClassNameToCoveredClassName:   false
        whitelist:
          addUncoveredFilesFromWhitelist:     true
          processUncoveredFilesFromWhitelist: false
          include:
            directories:
              'modelViews':
                'suffix': '.php'
              'utilities':
                'suffix': '.php'
              'models1':
                'suffix': '.php'
              'models':
                'suffix': '.inc'                
              'modelRepositories':
                'suffix': '.php'                
              'services':
                'suffix': '.php'                
              'controllers':
                'suffix': '.php'                                
              'views':
                'suffix': '.php'                
      report:
        format:   html
        options:
          target: build/behat-coverage
```
Still no love

**Comment by ek9** [comment]
Thank you for your report. The configuration in your 2nd comment is the one that should be valid. However I have investigated what is going on and there was a bug with `suffix` defaulting to `src` when not specified. This prevented the coverage from being generated. More information on issue #28 

Once PR #29 is merged, the issue would be fixed and you can use the config in the second comment.

For now, as a workaround, you need to specify empty `prefix` to get it to work, like this:

```yaml
            directories:
              'modelViews':
                'suffix': '.php'
                'prefix': ''
              'utilities':
                'suffix': '.php'
                'prefix': ''
```

Leaving this issue open until it #28 is closed.

Sorry for the trouble and please let me know if you have any further issues.

**Comment by ek9** [comment]
The fix has been merged upstream. As a shorthand (when using default `'.php'` suffix), you can also use:

```yaml
            directories:
              'modelViews': ~
              'utilities': ~'
              'models': 
                'suffix': '' # <--- use empty suffix so it will include all files                
              'modelRepositories': ~          
              'services': ~         
              'controllers': ~                                
              'views': ~              
```

Just make sure you have updated to `3.1.1` or `3.2.1` version of the package for this to work properly. 

Thank you for your report and do not hesitate to open an issue if you are still experiencing any problems. Closing.
