### ISSUE TITLE
Erroneous default prefix preventing files to be whitelisted

### ISSUE THREAD

**Issue by ek9** [leanphp/behat-code-coverage#28]
There is a bug when whitelisting files via configuration. If you do not supply `prefix` parameter, it defaulted to `src`, which only whitelisted files starting with `src`.

For example:

```yaml
whitelist:
  include:
    directories:
      'src':
        'suffix': '.php'
```
Would result in the extension adding default `'prefix': 'src'`. This would break whitelisting and would result in the following configuration instead:

```yaml
whitelist:
  include:
    directories:
      'src':
        'suffix': '.php'
        'prefix': 'src'
```

This has to be fixed.

The README and `behat.yml.dist` should be updated accordingly to include all information regarding the parameters.

Related issues #21 
Semi related issues #12 #11
